### ISSUE TITLE
redis_ingress: value of 'count' cannot be computed

### ISSUE THREAD

**Issue by BigAl** [terraform-community-modules/tf_aws_elasticache_redis#4]
```
Error running plan: 1 error(s) occurred:

* module.redis.aws_security_group_rule.redis_ingress: aws_security_group_rule.redis_ingress: value of 'count' cannot be computed
```
While attempting to use the option ` allowed_security_groups`

```module "redis" {
  source         = "github.com/terraform-community-modules/tf_aws_elasticache_redis?ref=1.0.1"
  env            = "${var.env}"
  name           = "${var.project}"
  redis_clusters = "2"
  redis_failover = "true"
  subnets        = "${var.data_subnet_list}"
  vpc_id         = "${var.vpc_id}"
  allowed_security_groups = ["${aws_security_group.instance.id}"]
}
```

I understand the issue here as the instance security group has not yet been created it can't be counted. Seems to be understood see https://github.com/hashicorp/terraform/issues/10857

This only failed for me when i destroyed and attempted to rebuild my stack from scratch. Previous as my `instance` already had been built it was not an issue.

I'm unsure of what exactly the solution to this is.

**Comment by davidkarban** [comment]
Got stuck with that too, as I understand from hashicorp/terraform#10857 there is actually only workarounds possible, I prefer the one with count value, because at least I`m not forced to populate subnets with fixed segurity group ids.

**Comment by kitsuneninetails** [comment]
Is this just not going to get fixed?  It's been a year and a half...  I will have to opt to not use the redis module at all, as this bug is a blocker.
