### ISSUE TITLE
Cannot apply a version constraint to module XXX because it has a non Registry URL.

### ISSUE THREAD

**Issue by LucaPrete** [terraform-community-modules/tf_aws_elasticache_redis#44]
Since the module is not published in the Terraform repos, but on GitHub it cannot be sourced using the keyword source together with the keyword version.

For example,

```
source  = "github.com/terraform-community-modules/tf_aws_elasticache_redis.git"
version = "~> 2.0"
```

does not work and should be changed to

```
source  = "github.com/terraform-community-modules/tf_aws_elasticache_redis.git?ref=v2.2.0"
```

The readme should be fixed accordingly

**Comment by pathouse** [comment]
looks like the README is correct and this can be closed
