### ISSUE TITLE
Feature proposal: using tf_sg modules

### ISSUE THREAD

**Issue by kamilboratynski** [terraform-community-modules/tf_aws_elasticache_redis#5]
As long, as there exists a `tf_aws_sg` [[1]] module; there is no reason to maintain `security_groups.tf` separately. Security groups should be rewritten and we should use `sg` module.

[1]: https://github.com/terraform-community-modules/tf_aws_sg

**Comment by antonbabenko** [comment]
Why would you want to make it as a dependency? This module is complete on its own, while it is completely possible to rely on other modules (like the one you mentioned) I don't think it is a good idea. Closing for now.
